# Generated by Django 4.2.5 on 2023-09-20 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', to_field='name'),
        ),
        migrations.AlterField(
            model_name='review',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reviewer', to_field='username'),
        ),
    ]
