# Generated by Django 4.2.5 on 2023-10-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_review_product_name_alter_review_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account',
            field=models.CharField(choices=[('B', 'Buyer'), ('S', 'Seller')], default='Buyer', max_length=1),
            preserve_default=False,
        ),
    ]
