# Generated by Django 4.2.5 on 2023-09-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_product_owner_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_owner',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=-1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sold_count',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
