# Generated by Django 4.2.5 on 2023-10-04 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customuser_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='description here', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='image url here', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default='seller username here', on_delete=django.db.models.deletion.CASCADE, to='main.customuser', to_field='username'),
            preserve_default=False,
        ),
    ]
