# Generated by Django 4.2.5 on 2023-11-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customuser_address_customuser_phone_number'),
        ('main', '0004_order_payment_orderitem'),
    ]

    operations = [
    ]
