# Generated by Django 4.2.5 on 2023-11-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customerfeedback_sellerfeedback_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='feedback_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sellerfeedback',
            name='feedback_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
