# Generated by Django 4.2.5 on 2023-10-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_review_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviewer',
        ),
    ]
