# Generated by Django 4.2.5 on 2023-11-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_customerfeedback_feedback_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerfeedback',
            name='easy_to_sell',
            field=models.BooleanField(verbose_name='Was it easy to list your products on our platform?'),
        ),
    ]
